# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d76bb9c4dc3b212719ba3addd4fa9a89141d66a3ed8e1bd9f8d8a6a1bc07dc0924b4fd90a56aee94273d940a3da18513ffcc64ea2db9a5c6dcf6aef365faa7c

test:
  secret_key_base: 80f89aa7da21a610843da90f479c154c2b9a64ddf18205f00a55a1d296591785324662b661648bf41b2849d7753c7398c0f83467bc6db3e0e73a074b594c6b2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
