Question.create(
    [
        { description: "",
          option_1: "",
          option_2: "",
          option_3: "",
          option_4: "",
          right_option: 1
        },
        { description: "Who won the most Man of the Match awards in the IPL?",
          option_1: "David Warner",
          option_2: "Virat Kohli",
          option_3: "Chris Gayle",
          option_4: "Rohit Sharma",
          right_option: 3
        },
        { description: "How many times did MS Dhoni appear in the IPL finals?",
          option_1: "7",
          option_2: "6",
          option_3: "8",
          option_4: "9",
          right_option: 3
        },
        { description: "Which team has successfully defended its title in the IPL?",
          option_1: "MI",
          option_2: "CSK",
          option_3: "KKR",
          option_4: "SRH",
          right_option: 2
        },
        { description: "Who was the player of the series in IPL 2014?",
          option_1: "Glenn Maxwell",
          option_2: "Shane Watson",
          option_3: "Andre Russell",
          option_4: "Virat Kohli",
          right_option: 1
        },
        { description: "Who is the highest Indian wicket-taker in the IPL?",
          option_1: "Harbhajan Singh",
          option_2: "Amit Mishra",
          option_3: "Lasith Malinga",
          option_4: "Piyush Chawla",
          right_option: 2
        },
        { description: "What is the highest total in the IPL?",
          option_1: "265",
          option_2: "264",
          option_3: "261",
          option_4: "263",
          right_option: 4
        },
        { description: "Which IPL season has the highest centuries?",
          option_1: "2011",
          option_2: "2015",
          option_3: "2016",
          option_4: "2012",
          right_option: 3
        },
        { description: "The slowest century in IPL came in how many balls?",
          option_1: "58",
          option_2: "68",
          option_3: "59",
          option_4: "66",
          right_option: 4
        },
        { description: " How many teams has Parthiv Patel featured in before IPL 2018?",
          option_1: "6",
          option_2: "5",
          option_3: "4",
          option_4: "3",
          right_option: 1
        },
        { description: "Which player among these has bowled the highest number of dot balls in the history of the IPL?",
          option_1: "Lasith Malinga",
          option_2: "Praveen Kumar",
          option_3: "Ashish Nehra",
          option_4: "Sunil Narine",
          right_option: 2
        },
        { description: "Against which team has Rohit Sharma taken a hat-trick?",
          option_1: "RCB",
          option_2: "MI",
          option_3: "CSK",
          option_4: "DD",
          right_option: 2
        },
        { description: "How many balls did Yusuf Pathan take to score a century against Mumbai Indians?",
          option_1: "40",
          option_2: "37",
          option_3: "34",
          option_4: "31",
          right_option: 2
        },
        { description: "Who scored the first ever century in the IPL?",
          option_1: "Suresh Raina",
          option_2: "Brendon McCullum",
          option_3: "Michael Hussey",
          option_4: "Virat Kohli",
          right_option: 2
        },
        { description: "Where was the final match of IPL 2017, between Mumbai Indians and Rising Pune Supergiants, played?",
          option_1: "Delhi",
          option_2: "Pune",
          option_3: "Mumbai",
          option_4: "Hyderabad",
          right_option: 4
            },
            { description: "Which bowler has won the Purple Cap in IPL 2015?",
              option_1: "Dwayne Bravo",
              option_2: "Amit Mishra",
              option_3: "Mohit Sharma",
              option_4: "Bhuvneshwar Kumar",
              right_option: 1
            },
            { description: "Who was the first bowler to take a hat-trick in the IPL?",
              option_1: "Lakshmipathy Balaji",
              option_2: "Amit Mishra",
              option_3: "Rohit Sharma",
              option_4: "Yuvraj Singh",
              right_option: 1
            },
            { description: "Who was the youngest player on the Kings XI Punjab roster in IPL 2008?",
              option_1: "Rishi Dhawan",
              option_2: "Ajitesh Agarwal",
              option_3: "Piyush Chawla",
              option_4: "Nitin Saini",
              right_option: 1
            },
            { description: "In IPL 2015, which of the following overseas' players was NOT the captain of his side?",
              option_1: "JP Duminy",
              option_2: "AB de Villiers",
              option_3: "Steve Smith",
              option_4: "David Warner",
              right_option: 2
            },
            { description: "Which batsman received the Orange Cap at the end of IPL 2008?",
              option_1: "Brendon McCullum",
              option_2: "Shaun Marsh",
              option_3: "Adam Gilchrist",
              option_4: "Sachin Tendulkar",
              right_option: 2
            },
            { description: "Which IPL team has Sohail Tanvir featured in?",
              option_1: "RR",
              option_2: "DD",
              option_3: "MI",
              option_4: "CSK",
              right_option: 1
            },
            { description: "To which country does the player who has taken the first ever 5 wicket haul in the IPL belong to?",
              option_1: "India",
              option_2: "Pakistan",
              option_3: "Sri Lanka",
              option_4: "England",
              right_option: 2
            },
            { description: "Who was the batsman who scored the most sixes in IPL 2008?",
              option_1: "Shaun Marsh",
              option_2: "Brendon McCullum",
              option_3: "Adam Gilchrist",
              option_4: "Sanath Jayasuriya",
              right_option: 4
            },
            { description: "Who was the first bowler in the IPL to give more than 50 runs in his 4 over spell?",
              option_1: "Ashok Dinda",
              option_2: "Lasith Malinga",
              option_3: "James Hopes",
              option_4: "Shane Warne",
              right_option: 3
            },
            { description: "Which fixture is the first match of IPL 2019?",
              option_1: "MI vs CSK",
              option_2: "CSK vs RCB",
              option_3: "CSK vs SRH",
              option_4: "SRH vs RCB",
              right_option: 2
            },
            { description: "What was the least total defended in the IPL?",
              option_1: "121",
              option_2: "118",
              option_3: "116",
              option_4: "120",
              right_option: 3
            },
            { description: "Against whom has Yuvraj singh taken hat-tricks?",
              option_1: "RCB, MI",
              option_2: "DC, MI",
              option_3: "MI, RR",
              option_4: "DC, RCB",
              right_option: 4
            },
            { description: "Who was the highest paid player in IPL 2012?",
              option_1: "Glenn Maxwell",
              option_2: "Ravindra Jadeja",
              option_3: "Yuvraj Singh",
              option_4: "Gautam Gambhir",
              right_option: 2
            },
            { description: "For how many franchises did Yusuf Pathan play?",
              option_1: "2",
              option_2: "3",
              option_3: "4",
              option_4: "1",
              right_option: 2
            },
            { description: "Which of the following was NOT a sponsor for IPL?",
              option_1: "DLF",
              option_2: "Pepsi",
              option_3: "Reliance",
              option_4: "Vivo",
              right_option: 3
            },
            { description: "How many times did CSK win the title?",
              option_1: "4",
              option_2: "3",
              option_3: "1",
              option_4: "2",
              right_option: 2
            },
            { description: "In which year was IPL not held in India?",
              option_1: "2009",
              option_2: "2008",
              option_3: "2016",
              option_4: "2013",
              right_option: 1
            },
            { description: "Which of the following teams won the most number of Fair Play Awards?",
              option_1: "KKR",
              option_2: "DD",
              option_3: "MI",
              option_4: "CSK",
              right_option: 1
            },
            { description: "In which season did CSK and RR got banned?",
              option_1: "9,10",
              option_2: "7,8",
              option_3: "10,11",
              option_4: "8,9",
              right_option: 1
            },
            { description: "For how many seasons did Deccan Chargers play?",
              option_1: "3",
              option_2: "4",
              option_3: "5",
              option_4: "6",
              right_option: 3
            },
            { description: "Who is the first Indian to win the Orange Cap in the IPL?",
              option_1: "Suresh Raina",
              option_2: "Paul Valthaty",
              option_3: "Virender Sehwag",
              option_4: "Sachin Tendulkar",
              right_option: 4
            },
            { description: "Against whom did Chris Gayle score 37 runs in a single over?",
              option_1: "Pavinder Awana",
              option_2: "Prashanth Parmeshwaran",
              option_3: "T Perera",
              option_4: "Ashok Dinda",
              right_option: 2
            },
            { description: "Most catches by a wicket keeper in the IPL?",
              option_1: "MS Dhoni",
              option_2: "Robin Uthappa",
              option_3: "Dinesh Karthik",
              option_4: "Parthiv Patel",
              right_option: 3
            },
            { description: "Which is the highest partnership by runs?",
              option_1: "ABD & Kohli",
              option_2: "Gayle & Kohli",
              option_3: "Gambhir & Lynn",
              option_4: "Warner & N.Ojha",
              right_option: 1
            },
            { description: "Who was the only bowler to bowl two maiden overs in IPL 2018?",
              option_1: "Andrew Tye",
              option_2: "Rashid Khan",
              option_3: "Lungi Ngidi",
              option_4: "Bhuvneshwar Kumar",
              right_option: 3
            },

            { description: "Who faced the most number of balls in IPL?",
              option_1: "Gautam Gambhir",
              option_2: "Suresh Raina",
              option_3: "Rohit Sharma",
              option_4: "Virat Kohli",
              right_option: 4
            },
            { description: "Who scored the fastest half-century in the IPL?",
              option_1: "Yusuf Pathan",
              option_2: "K L Rahul",
              option_3: "Sunil Narine",
              option_4: "Adam Gilchrist",
              right_option: 2
            },
            { description: "Which player won the Perfect Catch award in IPL 2018?",
              option_1: "Manish Pandey",
              option_2: "Virat Kohli",
              option_3: "Andrew Tye",
              option_4: "Trent Boult",
              right_option: 4
            },
            { description: "Who has the most catches as a fielder in the IPL?",
              option_1: "Suresh Raina",
              option_2: "Dwayne Bravo",
              option_3: "AB de Villiers",
              option_4: "Kieron Pollard",
              right_option: 1
            },
            { description: "Who bowled Kohli out in the IPL 2016 finals?",
              option_1: "Rashid Khan",
              option_2: "Bipul Sharma",
              option_3: "Bhuvneshwar Kumar",
              option_4: "Barinder Sran",
              right_option: 4
            },
            { description: "Can you name the highest paid Under-19 Player of IPL 2018?",
              option_1: "Sandeep Lamichhane",
              option_2: "Jaydev Unadkat",
              option_3: "Mujeeb Zardan",
              option_4: "Manish Pandey",
              right_option: 3
            },
            { description: "Who was the most expensive player of IPL 2008?",
              option_1: "MS Dhoni",
              option_2: "Gautam Gambhir",
              option_3: "Virender Sehwag",
              option_4: "Sachin Tendulkar",
              right_option: 1
            },
            { description: "Which player was bidded by all the franchises in the first season of IPL?",
              option_1: "Virat Kohli",
              option_2: "AB de Villiers",
              option_3: "Chris Gayle",
              option_4: "MS Dhoni",
              right_option: 4
            },
            { description: "Which among these is the home ground for SRH?",
              option_1: "Vijayawada",
              option_2: "Vishakapatnam",
              option_3: "Pune",
              option_4: "Kochi",
              right_option: 2
            },
            { description: "Which team played the most number of season openers?",
              option_1: "KKR",
              option_2: "CSK",
              option_3: "MI",
              option_4: "DD",
              right_option: 1
            },
            { description: "Who was the first captain for SRH?",
              option_1: "David Warner",
              option_2: "Kumar Sangakkara",
              option_3: "Cameron White",
              option_4: "Darren Sammy",
              right_option: 2
            },
            { description: "Who used the mongoose bat for first time in the IPL?",
              option_1: "Shaun Marsh",
              option_2: "Mike Hussey",
              option_3: "Mathew Hayden",
              option_4: "David Warner",
              right_option: 3
            },
            { description: "Who is the first Indian to register a century in the IPL?",
              option_1: "Suresh Raina",
              option_2: "Sachin Tendulkar",
              option_3: "Paul Valthaty",
              option_4: "Manish Pandey",
              right_option: 4
            },
            { description: "Which team won the match on boundary count because of tied super over?",
              option_1: "RR",
              option_2: "KKR",
              option_3: "MI",
              option_4: "DC",
              right_option: 1
            },
            { description: "Who won the emerging player for IPL 2018?",
              option_1: "Prithvi Shaw",
              option_2: "Rishab Pant",
              option_3: "Shreyas Iyer",
              option_4: "Shreyas Gopal",
              right_option: 4
            },
            { description: "Which team had the most number of captains?",
              option_1: "DD",
              option_2: "SRH",
              option_3: "MI",
              option_4: "KXIP",
              right_option: 2
            },
            { description: "Who hit the second longest six in the IPL?",
              option_1: "Albie Morkel",
              option_2: "Praveen Kumar",
              option_3: "Sunil Narine",
              option_4: "Chris Gayle",
              right_option: 2
            },
            { description: "Who hit the longest six in the IPL?",
              option_1: "Chris Gayle",
              option_2: "Albie Morkel",
              option_3: "MS Dhoni",
              option_4: "Kieron Pollard",
              right_option: 2
            },
            { description: "Which player featued in the 1st and 500th match in the IPL?",
              option_1: "Brendon McCullum",
              option_2: "Piyush Chawla",
              option_3: "Zaheer Khan",
              option_4: "Chris Gayle",
              right_option: 3
            },
            { description: "Who bowled the most number of dot balls in the IPL?",
              option_1: "Sunil Narine",
              option_2: "Bhuvneshwar Kumar",
              option_3: "Rashid Khan",
              option_4: "Praveen Kumar",
              right_option: 4
            },
            { description: "Who of the following was not a captain of SRH?",
              option_1: "Cameron White",
              option_2: "Kumar Sangakkara",
              option_3: "Shikhar Dhawan",
              option_4: "Dale Steyn",
              right_option: 4
            },
            { description: "Who is the youngest player in the history of the IPL?",
              option_1: "Mujeeb Zadran",
              option_2: "Rishab Pant",
              option_3: "Sandeep Lammichane",
              option_4: "Prithvi Shaw",
              right_option: 1
            },
            { description: "Which team bought Yuvraj Singh at the IPL 2016 Auction?",
              option_1: "KXIP",
              option_2: "RCB",
              option_3: "SRH",
              option_4: "MI",
              right_option: 3
            },
            { description: "Who bowled the fastest delivery in the IPL?",
              option_1: "Dale Steyn",
              option_2: "Pat Cummins",
              option_3: "Morne Morkel",
              option_4: "Kagiso Rabada",
              right_option: 2
            },
            { description: "Who Scored 5 consecutive half-centuries in IPL 2018?",
              option_1: "Ambati Rayudu",
              option_2: "Jos Buttler",
              option_3: "Kane Williamson",
              option_4: "Rishab Pant",
              right_option: 2
            },
            { description: "Who scored the most number of runs in the IPL?",
              option_1: "Suresh Raina",
              option_2: "Virat Kohli",
              option_3: "Gautam Gambhir",
              option_4: "Rohit Sharma",
              right_option: 1
            },
            { description: "Who hit the most number of sixes in the IPL?",
              option_1: "Chris Gayle",
              option_2: "AB de Villiers",
              option_3: "MS Dhoni",
              option_4: "Suresh Raina",
              right_option: 1
            },
            { description: "Who has the best batting strike rate in the IPL?",
              option_1: "Chris Gayle",
              option_2: "AB de Villiers",
              option_3: "Andre Russell",
              option_4: "Sunil Narine",
              right_option: 3
            },
            { description: "Who has the most number of half-centuries in the IPL?",
              option_1: "Suresh Raina",
              option_2: "Virat Kohli",
              option_3: "David Warner",
              option_4: "Gautam Gambhir",
              right_option: 4
            },
            { description: "Who hit the most number of fours in the IPL?",
              option_1: "Virat Kohli",
              option_2: "Suresh Raina",
              option_3: "David Warner",
              option_4: "Gautam Gambhir",
              right_option: 4
            },
            { description: "Who conceded the most number of runs in an innings in the IPL?",
              option_1: "Ishant Sharma",
              option_2: "Basil Thampi",
              option_3: "Ashok Dinda",
              option_4: "Parvinder Awana",
              right_option: 2
            },
            { description: "For which franchise is Stuart Binny currently playing?",
              option_1: "RCB",
              option_2: "SRH",
              option_3: "RR",
              option_4: "KXIP",
              right_option: 3
            },
            { description: "In which IPL season did Robin Uthappa get the Orange Cap?",
              option_1: "2010",
              option_2: "2013",
              option_3: "2014",
              option_4: "2018",
              right_option: 3
            },
            { description: "Which IPL team holds the record for most consecutive wins?",
              option_1: "KKR",
              option_2: "CSK",
              option_3: "RCB",
              option_4: "MI",
              right_option: 1
            },
            { description: "Which team holds the record for highest score in the IPL?",
              option_1: "SRH",
              option_2: "RCB",
              option_3: "KKR",
              option_4: "CSK",
              right_option: 2
            },
            { description: "Which team holds the record for lowest score in IPL?",
              option_1: "CSK",
              option_2: "KXIP",
              option_3: "DD",
              option_4: "RCB",
              right_option: 4
            },
            { description: "From which IPL stadium did Shah Rukh Khan get banned?",
              option_1: "M Chinnaswamy",
              option_2: "Feroz Shah Kotla",
              option_3: "Wankhede",
              option_4: "Chepauk",
              right_option: 3
            },
            { description: "Who is the founder of the IPL?",
              option_1: "N. Srinivasan",
              option_2: "Lalit Modi",
              option_3: "Rajeev Shukla",
              option_4: "Vijay Mallya",
              right_option: 2
            },
            { description: "Who is the auctioneer for the IPL Auction 2019?",
              option_1: "Villa Grisebach",
              option_2: "Hugh Edmeades",
              option_3: "Richard Madley",
              option_4: "Ketterer Kunst",
              right_option: 3
            },
            { description: "Who is the IPL auctioneer for 11 seasons who got sacked this year?",
              option_1: "Richard Madley",
              option_2: "Hugh Edmeades",
              option_3: "Dorothy Samhouse",
              option_4: "Maherid Dadha",
              right_option: 1
            },
            { description: "What is the highest number of runs scored by a batsman in an innings in IPL history?",
              option_1: "181",
              option_2: "161",
              option_3: "175",
              option_4: "178",
              right_option: 3
            },
            { description: "Who has the best bowling figures in an innings?",
              option_1: "Adam Zampa",
              option_2: "Anil Kumble",
              option_3: "Lasith Malinga",
              option_4: "Sohail Tanvir",
              right_option: 4
            },
            { description: "What is the best bowling figure recorded in IPL?",
              option_1: "6/12",
              option_2: "6/14",
              option_3: "6/10",
              option_4: "6/21",
              right_option: 2
            },
            { description: "Who has the record for the highest wicket taker in one IPL season?",
              option_1: "Dwayne Bravo",
              option_2: "Lasith Malinga",
              option_3: "Morne Mokel",
              option_4: "Bhuvneshwar Kumar",
              right_option: 1
            },
            { description: "What is the highest number of wickets taken by a bowler in one IPL season?",
              option_1: "29",
              option_2: "37",
              option_3: "32",
              option_4: "21",
              right_option: 3
            },
            { description: "Which of the following is RCB’s homeground?",
              option_1: "Chidambaram",
              option_2: "Chinnasamy",
              option_3: "Eden Gardens",
              option_4: "Wankhede",
              right_option: 2
            },
            { description: "What is the maximum number of teams ever participated in IPL?",
              option_1: "8",
              option_2: "12",
              option_3: "10",
              option_4: "9",
              right_option: 3
            },
            { description: "Who among these is NOT an owner of KKR?",
              option_1: "Shah Rukh Khan",
              option_2: "Sanjay Sharma",
              option_3: "Jay Mehta",
              option_4: "Juhi Chawla",
              right_option: 2
            },
            { description: "Who has the highest individual score in a match in IPL 2018?",
              option_1: "Rishab Pant",
              option_2: "Shane Watson",
              option_3: "Ambati Rayudu",
              option_4: "Kane Williamson",
              right_option: 1
            },
            { description: "Which of these Australian players was the head coach of Gujarat Lions?",
              option_1: "Michael Hussey",
              option_2: "Brad Hodge",
              option_3: "Matthew Hayden",
              option_4: "Ricky Ponting",
              right_option: 2
            },
            { description: "Who is the oldest player to debut in IPL?",
              option_1: "Brad Hogg",
              option_2: "Adam Gilchrist",
              option_3: "Pravin Tambe",
              option_4: "Anil Kumble",
              right_option: 3
            },
            { description: "Who among these was never an IPL owner?",
              option_1: "Deccan Chronicle",
              option_2: "India Cements",
              option_3: "Videocon",
              option_4: "Intex Smart World",
              right_option: 3
            },
            { description: "Who scored a total of 300+ runs in every IPL season till now?",
              option_1: "Suresh Raina",
              option_2: "Rohit Sharma",
              option_3: "Virat Kohli",
              option_4: "Gautam Gambhir",
              right_option: 1
            },
            { description: "Which among is the slogan for KKR?",
              option_1: "Halla Bol",
              option_2: "Korbo Lorbo Jeetbo Re",
              option_3: "Whistle Podu",
              option_4: "Khelo Front Foot Pe",
              right_option: 2
            },
            { description: "What is the new name of Delhi Daredevils?",
              option_1: "Delhi Dynamos",
              option_2: "Delhi Crusaders",
              option_3: "Delhi Capitals",
              option_4: "Delhi Giants",
              right_option: 3
            },
            { description: "Who is the owner of Delhi Capitals?",
              option_1: "GMR Group",
              option_2: "Jaypee Group",
              option_3: "L&T",
              option_4: "Maruti",
              right_option: 1
            },
            { description: "Against which team did Jasprit Bumrah debut in the IPL?",
              option_1: "DD",
              option_2: "SRH",
              option_3: "KKR",
              option_4: "RCB",
              right_option: 4
            },
            { description: "Who has the most number of hat-tricks in the history of the IPL?",
              option_1: "Lasith Malinga",
              option_2: "Yuvraj Singh",
              option_3: "Pragyan Ojha",
              option_4: "Amit Mishra",
              right_option: 4
            },
            { description: "Who has hit 23 runs in the final over of the final match in IPL 2016 bowled by Watson?",
              option_1: "Moises Henriques",
              option_2: "Ben Cutting",
              option_3: "Yuvraj Singh",
              option_4: "Naman Ojha",
              right_option: 2
            },
            { description: "Who has hit all 6 balls of the first over for a 4?",
              option_1: "Gautam Gambhir",
              option_2: "Virender Sehwag",
              option_3: "David Warner",
              option_4: "Adam Gilchrist",
              right_option: 4
            },
            { description: "Which of these players featured in the most number of IPL title wins?",
              option_1: "MS Dhoni",
              option_2: "Karn Sharma",
              option_3: "Rohit Sharma",
              option_4: "Gautam Gambhir",
              right_option: 3
            },
            { description: "Which of the following cricketers is not a coach for an IPL franchise?",
              option_1: "Gary Kirsten",
              option_2: "Jacque Kallis",
              option_3: "Ricky Ponting",
              option_4: "Ravi Shastri",
              right_option: 4
            },
            { description: "What is the total number of superovers played in the IPL?",
              option_1: "7",
              option_2: "8",
              option_3: "9",
              option_4: "10",
              right_option: 1
            },
            { description: "Which of the following players are not part of the IPL?",
              option_1: "Paul Collingwood",
              option_2: "Glenn McGrath",
              option_3: "Joe Root",
              option_4: "Sanjay Bangar",
              right_option: 3
            }
    ]
)